# -*- coding: utf-8 -*-
"""Ejericicio1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZIGQjOiS_x_bPy5WINgZq46boKqg5gX

# **Ejercicio 1b)**

###Trabajo realizado por los alumnos:
#####    Juárez Torres Carlos Alberto ------------ 318013712
#####    Kano Chavira Nicolás -------------------- 315319204
#####    Méndez Saucedo Abigail ------------------ 421098260
#####    Partida Contreras Marían de los Ángeles - 421095630
"""

def raíz_secante(fun,x0,x1):
  """
      Este programa regresa la raíz de una función a partir de dos puntos
       iniciales distintos
    
    Parameters
    ----------
    x1: float/int punto inicial
    x0: float/int punto inicial
    fun: function función a trabajar

    Returns
    -------
    x1: float raiz de la función
  """
  if x1==x0:
    return print("Por favor ingrese puntos iniciales distintos")
  k=0
  tol=0.001
  while (abs(x1-x0)>tol):
    aux1=x0
    aux2=x1
    x1= aux2-((fun(aux2)*(aux2-aux1))/(fun(aux2)-fun(aux1)))
    x0=aux2
    k+=1
    if k>100:
      print("Favor de elegir nuevos puntos iniciales")
      break
  return x1

def cuadrado(x):
  y=(x**2)-(4*x)+3
  return y

raíz_secante(cuadrado,22,2)