
#Laboratorio: Laboratorio 1
#Integrantes:
# Juarez Torres Carlos Alberto (JTCA)
# Vega González Pedro Rubén    (VGPR)

#Nombre del programa: Beta-galactosodasa

#Seleccion de Bibliotecas

import numpy as np
import matplotlib.pyplot as plt

#generación de varaibles
Tau=np.random.randint(1,100, size = 100)
A=np.random.random_sample(size=100)
t=np.random.uniform(0, 4 , size=5)
tT=[]#array vacia para añadir soluciones
i=0
#ciclo que llena a tT
while i<100:
    tT.append(-t/Tau[(i)])
    i+=1
#calculo de e^(tT)
etT=np.exp(tT)
#array con valores para el color
cl=["blue","orange","purple","brown","pink","gray","olive","cyan", "green","red"]
V=(1-etT)
W=(etT-1+tT)
x=t
#generación de la grafica V
plt.scatter(x,V[0], c=cl[0], marker=".")
plt.scatter(x,V[1], c=cl[1], marker=".")
plt.scatter(x,V[2], c=cl[2], marker=".")
plt.scatter(x,V[3], c=cl[3], marker=".")
plt.scatter(x,V[4], c=cl[4], marker=".")
plt.scatter(x,V[5], c=cl[5], marker=".")
plt.scatter(x,V[6], c=cl[6], marker=".")
plt.scatter(x,V[7], c=cl[7], marker=".")
plt.scatter(x,V[8], c=cl[8], marker=".")
plt.scatter(x,V[9], c=cl[9], marker=".")
plt.scatter(x,V[9], c=cl[9], marker=".")
plt.scatter(x,V[0], c=cl[0], marker=".")
plt.scatter(x,V[10], c=cl[0], marker=".")
plt.scatter(x,V[11], c=cl[1], marker=".")
plt.scatter(x,V[12], c=cl[2], marker=".")
plt.scatter(x,V[13], c=cl[3], marker=".")
plt.scatter(x,V[14], c=cl[4], marker=".")
plt.scatter(x,V[15], c=cl[5], marker=".")
plt.scatter(x,V[16], c=cl[6], marker=".")
plt.scatter(x,V[17], c=cl[7], marker=".")
plt.scatter(x,V[18], c=cl[8], marker=".")
plt.scatter(x,V[19], c=cl[9], marker=".")
plt.scatter(x,V[20], c=cl[0], marker=".")
plt.scatter(x,V[21], c=cl[1], marker=".")
plt.scatter(x,V[22], c=cl[2], marker=".")
plt.scatter(x,V[23], c=cl[3], marker=".")
plt.scatter(x,V[24], c=cl[4], marker=".")
plt.scatter(x,V[25], c=cl[5], marker=".")
plt.scatter(x,V[26], c=cl[6], marker=".")
plt.scatter(x,V[27], c=cl[7], marker=".")
plt.scatter(x,V[28], c=cl[8], marker=".")
plt.scatter(x,V[29], c=cl[9], marker=".")
plt.scatter(x,V[30], c=cl[0], marker=".")
plt.scatter(x,V[31], c=cl[1], marker=".")
plt.scatter(x,V[32], c=cl[2], marker=".")
plt.scatter(x,V[33], c=cl[3], marker=".")
plt.scatter(x,V[34], c=cl[4], marker=".")
plt.scatter(x,V[35], c=cl[5], marker=".")
plt.scatter(x,V[36], c=cl[6], marker=".")
plt.scatter(x,V[37], c=cl[7], marker=".")
plt.scatter(x,V[38], c=cl[8], marker=".")
plt.scatter(x,V[39], c=cl[9], marker=".")
plt.scatter(x,V[40], c=cl[0], marker=".")
plt.scatter(x,V[41], c=cl[1], marker=".")
plt.scatter(x,V[42], c=cl[2], marker=".")
plt.scatter(x,V[43], c=cl[3], marker=".")
plt.scatter(x,V[44], c=cl[4], marker=".")
plt.scatter(x,V[45], c=cl[5], marker=".")
plt.scatter(x,V[46], c=cl[6], marker=".")
plt.scatter(x,V[47], c=cl[7], marker=".")
plt.scatter(x,V[48], c=cl[8], marker=".")
plt.scatter(x,V[49], c=cl[9], marker=".")
plt.scatter(x,V[50], c=cl[0], marker=".")
plt.scatter(x,V[51], c=cl[1], marker=".")
plt.scatter(x,V[52], c=cl[2], marker=".")
plt.scatter(x,V[53], c=cl[3], marker=".")
plt.scatter(x,V[54], c=cl[4], marker=".")
plt.scatter(x,V[55], c=cl[5], marker=".")
plt.scatter(x,V[56], c=cl[6], marker=".")
plt.scatter(x,V[57], c=cl[7], marker=".")
plt.scatter(x,V[58], c=cl[8], marker=".")
plt.scatter(x,V[59], c=cl[9], marker=".")
plt.scatter(x,V[60], c=cl[0], marker=".")
plt.scatter(x,V[61], c=cl[1], marker=".")
plt.scatter(x,V[62], c=cl[2], marker=".")
plt.scatter(x,V[63], c=cl[3], marker=".")
plt.scatter(x,V[64], c=cl[4], marker=".")
plt.scatter(x,V[65], c=cl[5], marker=".")
plt.scatter(x,V[66], c=cl[6], marker=".")
plt.scatter(x,V[67], c=cl[7], marker=".")
plt.scatter(x,V[68], c=cl[8], marker=".")
plt.scatter(x,V[69], c=cl[9], marker=".")
plt.scatter(x,V[70], c=cl[0], marker=".")
plt.scatter(x,V[71], c=cl[1], marker=".")
plt.scatter(x,V[72], c=cl[2], marker=".")
plt.scatter(x,V[73], c=cl[3], marker=".")
plt.scatter(x,V[74], c=cl[4], marker=".")
plt.scatter(x,V[75], c=cl[5], marker=".")
plt.scatter(x,V[76], c=cl[6], marker=".")
plt.scatter(x,V[77], c=cl[7], marker=".")
plt.scatter(x,V[78], c=cl[8], marker=".")
plt.scatter(x,V[79], c=cl[9], marker=".")
plt.scatter(x,V[80], c=cl[0], marker=".")
plt.scatter(x,V[81], c=cl[1], marker=".")
plt.scatter(x,V[82], c=cl[2], marker=".")
plt.scatter(x,V[83], c=cl[3], marker=".")
plt.scatter(x,V[84], c=cl[4], marker=".")
plt.scatter(x,V[85], c=cl[5], marker=".")
plt.scatter(x,V[86], c=cl[6], marker=".")
plt.scatter(x,V[87], c=cl[7], marker=".")
plt.scatter(x,V[88], c=cl[8], marker=".")
plt.scatter(x,V[89], c=cl[9], marker=".")
plt.scatter(x,V[90], c=cl[0], marker=".")
plt.scatter(x,V[91], c=cl[1], marker=".")
plt.scatter(x,V[92], c=cl[2], marker=".")
plt.scatter(x,V[93], c=cl[3], marker=".")
plt.scatter(x,V[94], c=cl[4], marker=".")
plt.scatter(x,V[95], c=cl[5], marker=".")
plt.scatter(x,V[96], c=cl[6], marker=".")
plt.scatter(x,V[97], c=cl[7], marker=".")
plt.scatter(x,V[98], c=cl[8], marker=".")
plt.scatter(x,V[99], c=cl[9], marker=".")
plt.show()#impresión de grafica V
#Generación de grafica W
plt.scatter(x,W[0], c=cl[0], marker=".")
plt.scatter(x,W[1], c=cl[1], marker=".")
plt.scatter(x,W[2], c=cl[2], marker=".")
plt.scatter(x,W[3], c=cl[3], marker=".")
plt.scatter(x,W[4], c=cl[4], marker=".")
plt.scatter(x,W[5], c=cl[5], marker=".")
plt.scatter(x,W[6], c=cl[6], marker=".")
plt.scatter(x,W[7], c=cl[7], marker=".")
plt.scatter(x,W[8], c=cl[8], marker=".")
plt.scatter(x,W[9], c=cl[9], marker=".")
plt.scatter(x,W[9], c=cl[9], marker=".")
plt.scatter(x,W[0], c=cl[0], marker=".")
plt.scatter(x,W[10], c=cl[0], marker=".")
plt.scatter(x,W[11], c=cl[1], marker=".")
plt.scatter(x,W[12], c=cl[2], marker=".")
plt.scatter(x,W[13], c=cl[3], marker=".")
plt.scatter(x,W[14], c=cl[4], marker=".")
plt.scatter(x,W[15], c=cl[5], marker=".")
plt.scatter(x,W[16], c=cl[6], marker=".")
plt.scatter(x,W[17], c=cl[7], marker=".")
plt.scatter(x,W[18], c=cl[8], marker=".")
plt.scatter(x,W[19], c=cl[9], marker=".")
plt.scatter(x,W[20], c=cl[0], marker=".")
plt.scatter(x,W[21], c=cl[1], marker=".")
plt.scatter(x,W[22], c=cl[2], marker=".")
plt.scatter(x,W[23], c=cl[3], marker=".")
plt.scatter(x,W[24], c=cl[4], marker=".")
plt.scatter(x,W[25], c=cl[5], marker=".")
plt.scatter(x,W[26], c=cl[6], marker=".")
plt.scatter(x,W[27], c=cl[7], marker=".")
plt.scatter(x,W[28], c=cl[8], marker=".")
plt.scatter(x,W[29], c=cl[9], marker=".")
plt.scatter(x,W[30], c=cl[0], marker=".")
plt.scatter(x,W[31], c=cl[1], marker=".")
plt.scatter(x,W[32], c=cl[2], marker=".")
plt.scatter(x,W[33], c=cl[3], marker=".")
plt.scatter(x,W[34], c=cl[4], marker=".")
plt.scatter(x,W[35], c=cl[5], marker=".")
plt.scatter(x,W[36], c=cl[6], marker=".")
plt.scatter(x,W[37], c=cl[7], marker=".")
plt.scatter(x,W[38], c=cl[8], marker=".")
plt.scatter(x,W[39], c=cl[9], marker=".")
plt.scatter(x,W[40], c=cl[0], marker=".")
plt.scatter(x,W[41], c=cl[1], marker=".")
plt.scatter(x,W[42], c=cl[2], marker=".")
plt.scatter(x,W[43], c=cl[3], marker=".")
plt.scatter(x,W[44], c=cl[4], marker=".")
plt.scatter(x,W[45], c=cl[5], marker=".")
plt.scatter(x,W[46], c=cl[6], marker=".")
plt.scatter(x,W[47], c=cl[7], marker=".")
plt.scatter(x,W[48], c=cl[8], marker=".")
plt.scatter(x,W[49], c=cl[9], marker=".")
plt.scatter(x,W[50], c=cl[0], marker=".")
plt.scatter(x,W[51], c=cl[1], marker=".")
plt.scatter(x,W[52], c=cl[2], marker=".")
plt.scatter(x,W[53], c=cl[3], marker=".")
plt.scatter(x,W[54], c=cl[4], marker=".")
plt.scatter(x,W[55], c=cl[5], marker=".")
plt.scatter(x,W[56], c=cl[6], marker=".")
plt.scatter(x,W[57], c=cl[7], marker=".")
plt.scatter(x,W[58], c=cl[8], marker=".")
plt.scatter(x,W[59], c=cl[9], marker=".")
plt.scatter(x,W[60], c=cl[0], marker=".")
plt.scatter(x,W[61], c=cl[1], marker=".")
plt.scatter(x,W[62], c=cl[2], marker=".")
plt.scatter(x,W[63], c=cl[3], marker=".")
plt.scatter(x,W[64], c=cl[4], marker=".")
plt.scatter(x,W[65], c=cl[5], marker=".")
plt.scatter(x,W[66], c=cl[6], marker=".")
plt.scatter(x,W[67], c=cl[7], marker=".")
plt.scatter(x,W[68], c=cl[8], marker=".")
plt.scatter(x,W[69], c=cl[9], marker=".")
plt.scatter(x,W[70], c=cl[0], marker=".")
plt.scatter(x,W[71], c=cl[1], marker=".")
plt.scatter(x,W[72], c=cl[2], marker=".")
plt.scatter(x,W[73], c=cl[3], marker=".")
plt.scatter(x,W[74], c=cl[4], marker=".")
plt.scatter(x,W[75], c=cl[5], marker=".")
plt.scatter(x,W[76], c=cl[6], marker=".")
plt.scatter(x,W[77], c=cl[7], marker=".")
plt.scatter(x,W[78], c=cl[8], marker=".")
plt.scatter(x,W[79], c=cl[9], marker=".")
plt.scatter(x,W[80], c=cl[0], marker=".")
plt.scatter(x,W[81], c=cl[1], marker=".")
plt.scatter(x,W[82], c=cl[2], marker=".")
plt.scatter(x,W[83], c=cl[3], marker=".")
plt.scatter(x,W[84], c=cl[4], marker=".")
plt.scatter(x,W[85], c=cl[5], marker=".")
plt.scatter(x,W[86], c=cl[6], marker=".")
plt.scatter(x,W[87], c=cl[7], marker=".")
plt.scatter(x,W[88], c=cl[8], marker=".")
plt.scatter(x,W[89], c=cl[9], marker=".")
plt.scatter(x,W[90], c=cl[0], marker=".")
plt.scatter(x,W[91], c=cl[1], marker=".")
plt.scatter(x,W[92], c=cl[2], marker=".")
plt.scatter(x,W[93], c=cl[3], marker=".")
plt.scatter(x,W[94], c=cl[4], marker=".")
plt.scatter(x,W[95], c=cl[5], marker=".")
plt.scatter(x,W[96], c=cl[6], marker=".")
plt.scatter(x,W[97], c=cl[7], marker=".")
plt.scatter(x,W[98], c=cl[8], marker=".")
plt.scatter(x,W[99], c=cl[9], marker=".")
plt.show() #impresión de grafica W


#Fin del programa